function lingua()
{
	this.tutorial_frame="These are the frame or frames of animation that we are creating. The scene that we created so far in our area of ​​work is the starting point, if you click on a frame following the current one (zero if no frame you have already clicked no frames), not necessarily consecutive, for example, we can move, rotate, scale or any other change of scene, this new reorganization of the image will be the end of our animation. So to make an animation does not need to change every frame (or frames) from point A to point B, but only enough to create the scene of the initial frame (zero) and that of the final frame (which you will select). All intermediate frames will be created automatically by the software distributed fairly the changes of all the frames that are between the start and the end of the animation.<br>To prove, once you create an object, click on a frame, then in the horizontal bar below click on the right mouse button and choose to create an interpolation.";
	this.tutorial_agg_frame="Write here the number of frames you want to add to those already present";
	this.tutorial_agg_frame_button="Click here to add frames written in left field";
	this.tutorial_ms="Enter the time in milliseconds of duration of each frame (1 second = 1000 milliseconds)";
	this.tutorial_ultimo_frame = "Enter the number of the last frame, where it will stop the animation";
	this.errore_ins_ms = "This field contains the time in milliseconds for each frame must be numeric";
	this.errore_ins_frame = "This field contains the number of the last frame of the animation must be numeric";
	this.errore_base_altezza = "Base and height should be numbers!"
	this.errore_trasparenza = "background transparency must be a value between zero and one (including decimals)";
	this.tutorial_inizio = "Click on one of the drawing tools in the upper right";
	this.come_disegnare = "To draw a shape / text just place the mouse in the box below (white if you have not changed the color) click on the spot where you would like to draw the shape and choice, while continuing to hold, move the mouse in the plan to decide the size of the figure ";
	this.tutorial_disegnare_linee = "click in the box below (white if you have not changed the color) to create the various points that would make the call when others do not want to create multiple points hit 'enter' to end";
	this.tutorial_selezione = "click on objects designed to be able to select. Once selected you can move, zoom in and the object. Moreover, once the selected object, if you activate the detail screen, you can access the more advanced changes." ;
	this.tutorial_multi_selezione = "Click somewhere in the box below (white if you have not changed the color) and holding the button, move the mouse to create an area within which objects can be selected and then, from the detail screen to be moved, rotated and scaled. "
	this.tutorial_over_selezioni = "this is not useful to create geometric shapes or images, but to choose existing ones so that they can change";
	this.sblocca_animazioni = "<br> ------------------ <br> to draw just move the mouse in the workspace, click, hold and drag the cursor to then release the button when finished. <br> may happen that the browser interprets the tascinamento mouse as an attempt to select one or more page items, making it impossible to complete the operation launched in HCA. In these cases just hit the Enter or Esc to complete the operation. "
	this.tutorial_cerchio = "This tool is used to create regular circles" + this.sblocca_animazioni;
	this.tutorial_quadrato = "This tool is used to create quadrilaterals" + this.sblocca_animazioni;
	this.tutorial_ellisse = "this tool is used to create objects of oval / elliptical"+this.sblocca_animazioni;
	this.tutorial_testo = "this tool is used to create text" + this.sblocca_animazioni;
	this.tutorial_poligono = "This tool is used to create regular polygons"+this.sblocca_animazioni;
	this.tutorial_linea = "This tool is used to create lines and paths. <br> To draw a line just click in the workspace where you want the points and when finished press enter or esc.";
	this.tutorial_immagine = "This tool is used to load images in the work";
	this.tutorial_multiselezione = "This tool allows you to select multiple items together to be able to then move, rotate and scale";
	this.tutorial_colore_sfondo = "clicking here will open a window where you can change the background color of the objects you're going to create";
	this.tutorial_colore_bordo = "clicking here will open a window where you can change the outline color of the objects you're going to create";
	this.tutorial_colore_area_lavoro = "clicking here will open a window where you can change the background color of the workspace, the changes will be visible only after you hit the button 'Edit workspace'";
	this.tutorial_spessore_area_lavoro = "When you select an object it surrounds a green line, with this field you can choose the thickness of the line quieted";
	this.tutorial_base_area_lavoro = "insert here the width in px of your project (workspace), the changes will be visible only after you hit the button 'Edit workspace'";
	this.tutorial_altezza_area_lavoro = "insert here the height in px of your project (workspace), the changes will be visible only after you hit the button 'Edit workspace'";
	this.tutorial_button_area_lavoro = "clicking here you can make visible changes in height, width and color of the work";
	this.tutorial_alpha_area_lavoro = "insert here a value between zero and one to set the transparency of the work (if zero is transparent)";
	this.tutorial_annulla = "clicking here you can undo the last operation done";
	this.tutorial_ripeti = "clicking here you can restore a previously undone operation";
	this.tutorial_play = "Click here to start the animation. If you are positioned on the last frame of your animation and press play you will not see anything moving because when the animation starts immediately terminate. Click on frame zero, and then press play (the key where you are located) to see your animation entirely. "
	this.tutorial_stop = "Click here to stop the animation in progress";
	this.tutorial_dettagli = "Click here to open the detail screen of the selected object. The screen will remain blank if you have not selected any object. To select an object click on the tool with your mouse cursor and finally click on an object in the frame work and you'll see the screen with all the details (editable) object ";
	this.tutorial_tutorial = "Click here to open the window that tells you how to best use the program";
	this.opzioni_documento = "Document Options";
	this.creazione_oggetto = "Create Object";
	this.modifica_area_lavoro = "Edit Workspace";
	this.tutorial_errore = "this button will light when you found an error in the program. If this happens, follow the steps to report it!"
	this.tutorial_esporta = "Click here to export your work in a format (html) that you can use for your web pages. also will open a dropdown where you can choose to export the project as an animation or still image."
	this.tutorial_salva = "Click here to save your work in a format (XML) that you can only use the html canvas animation. This function is useful to stop working on the project and save the current state to reopen and modify them later ";
	this.tutorial_apri = "With this button we can access a menu that will allow us to restore a previously saved job (with the save button)."
	this.color = "Color";
	this.trasparenza = "Transparency";
	this.larghezza = "width";
	this.altezza = "Height";
	this.spessore = "Marking";
	this.dettagli_oggetto = "Item details";
	this.aggiunta_frame = "Add frame";
	this.durata_frame = "Frame Duration (ms)";
	this.frame_finale = "Frame End";
	this.cambia_colore = "Change Color";
	this.contorno = "Outline";
	this.riempimento = "Fill";
	this.spessore_bordo = "border width";
	this.composizione = "Composition";
	this.posizione_x = "Position x";
	this.posizione_y = "Position y";
	this.angolo = "Angle";
	this.raggio = "Ray";
	this.angolo_inizio = "start angle";
	this.angolo_fine = "end angle";
	this.tipo_tracciato = "path type";
	this.tipo_chiusura_tracciato = "type closing track";
	this.tipo_angoli_tracciato = "type track corners";
	this.gradiente_riempimento = "Gradient Fill";
	this.gradiente_contorno = "gradient boundary";
	this.aperto = "Open";
	this.chiuso = "Closed";
	this.base = "Base";
	this.smussatura_angoli = "Chamfering corners";
	this.numero_angoli = "Number of angles";
	this.testo = "text";
	this.font = "Fonts";
	this.nessun_errore = "No errors found";
	this.errore_doc = '"<h1><strong>Error</strong> </h1> Error in <br> \'last procedure performed. <br> It could be nothing, like for example if you have a blank or zero field of all details, try pressing the cancel button and if the \'error occurs again help us to improve the program. <br> <a href = \'mailto:iacopo.guarneri@alice.it?subject=Error HCA&body= Hi, I found a problem in the program (Canvas Html Animation) which introduces the following error code:%0d%0a %0d%0a"+storico[punta_storico]+" \'> Error Report </a> <br> < br> If not, write in <a href=\'index.php/contatti\'> Contacts </a>, click on the item \'Contact Form\' to write, to help us in solving this problem please send us the following error code: <br> <div style=\'height:50px; overflow:auto; border:3px dashed #444; padding:15px;\'> "+storico[punta_storico]+" </div> "';
	this.esporta = "Export";
	this.animazione = "Animation";
	this.immagine_fissa = "Still Image";
	this.apri = "Open";
	this.inserisci_testo = "Enter the text";
	this.lineare = "Linear";
	this.radiale = "Radial";
	this.annulla = "Undo (Ctrl + z)";
	this.ripeti = "Repeat (ctrl + y)";
	this.mostra_errori = "Show if there were any errors in the program";
	this.apri_title = "Open project saved (xml)";
	this.salva_title = "Save Project (xml)";
	this.esporta_title = "Export Project (html)";
	this.riempimento_title = "Change the object color";
	this.contorno_title = "Change the color of the border";
	this.selezione = "Select objects";
	this.cerchio = "Draw circles";
	this.quadrato = "Draw squares";
	this.ovale = "Draw Oval";
	this.poligono = "Draw Polygon";
	this.testo = "Draw text";
	this.linea = "Draw lines";
	this.immagine = "Import Pictures";
	this.multi_selezione = "Select Multiple Objects";
	this.timeline_label = "Timeline";
	this.crea_n_frame = "Create sublayers of this frame interpolation on";
	this.distruggi_n_frame = "Destroy interpolation on the sublayers of this frame";
	this.aggiungi = "Add";
	this.mostra_nascondi_sottolivelli = "Show / hide sublevels by the timeline view";
	this.blocca_sblocca = "Lock / Unlock level";
	this.mostra_nascondi = "Show / Hide layer";
	this.sposta_su = "Move up a level";
	this.sposta_giu = "Move down a level";
	this.sottolivello = "Makes a sublevel of the level that is above";
	this.livello = "Selecting a frame <img src='immagini/frame.png'> poosizionandoti and the timeline of a level (how are you doing now) with the right mouse button you can open a menuche will allow you to create or destroy a transition of your animation. "
	this.interpolazione = "These symbols indicate where you have created a transition in your movie, by clicking and holding down the mouse button you can move it earlier or later in the timeline."
	this.scala_del = "Scale";
	this.ruota_di = "wheel";
	this.gradi = "Degrees";
	this.esegui = "Run";
	this.sposta_di = "Move objects";
	this.line_tool = "Transform the selected point in a hard corner";
	this.bez_tool = "Transform the selected point in a cut corner";
	this.aggiungi_punto = "Add a line to your";
	this.rimuovi_punto = "Remove a point from your line";
}
